### ISSUE TITLE
Roadmap of your implementation (+ questions)

### ISSUE THREAD

**Issue by yvan-sraka** [IlesESGI/raytracer#1]
You chose `libray` project: _a fully-featured raytracing library_

Right now you have an implemented based on https://bheisler.github.io/post/writing-raytracer-in-rust-part-1/

I really expect from you to provide:

- **Make the computation parallel**
- **Have a progress bar of the raytracing process and provide large test**

As a bonus can you:

- Handle other 3D formats (currently, your program take a `json`)
- Be able to change the camera position and angle in the scene with the mouse (use OpenGL to display scene while user move mouse)

Question:

- **Is OpenGL use raytracing to render 3D scene? How does this work? What the benefits of both methods?**

- **What is shadering? How is it computed? Why smart people do raytracing in shaders?**

**Comment by IlesESGI** [comment]
Thanks for your comments

I just added computation parallelism + a progress bar and a timer to check execution time.

I have a problem with the parallelism because the execution time with the parallelism is way greater than without... that's weird.

The questions you asked us are for the exam or do we have to reply here ?

**Comment by yvan-sraka** [comment]
You have to **answer the questions** in the `README.md` of your project :wink:

**Comment by IlesESGI** [comment]
Everything you asked is done !
